name: medical_delivery_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  fl_chart: ^1.1.0
  shared_preferences: ^2.5.3
  http: ^1.5.0
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  qr_flutter: ^4.1.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_places_flutter: ^2.1.1
  google_fonts: ^6.3.1
  google_maps_flutter: ^2.13.1
  permission_handler: ^12.0.1
  flutter_map: ^8.2.1
  url_launcher: ^6.3.2
  socket_io_client: ^3.1.2
  audioplayers: ^6.5.1
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

# ðŸ”¥ LAUNCHER ICON CONFIG (TOP LEVEL â€” VERY IMPORTANT)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/appstore.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/splashimage.png
    - assets/homeprofile.png
    - assets/profileimage.png
    - assets/mapimage.png
    - assets/medicineimage.png
    - assets/scannerimage.png
    - assets/chatimage2.png
    - assets/chatimage1.png
    - assets/chat.png
    - assets/chat2.png
    - assets/QR1.jpg
    - assets/order_alert.mp3
